CREATE OR REPLACE FUNCTION prevent_event_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% rows are append-only in BorderFlow.', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_milestone_immutable ON milestone;
CREATE TRIGGER trg_milestone_immutable
    BEFORE UPDATE OR DELETE ON milestone
    FOR EACH ROW
    EXECUTE FUNCTION prevent_event_mutation();

DROP TRIGGER IF EXISTS trg_handover_immutable ON handover;
CREATE TRIGGER trg_handover_immutable
    BEFORE UPDATE OR DELETE ON handover
    FOR EACH ROW
    EXECUTE FUNCTION prevent_event_mutation();

ALTER TABLE app_user REPLICA IDENTITY FULL;
ALTER TABLE client REPLICA IDENTITY FULL;
ALTER TABLE vehicle REPLICA IDENTITY FULL;
ALTER TABLE driver REPLICA IDENTITY FULL;
ALTER TABLE consignment REPLICA IDENTITY FULL;
ALTER TABLE container REPLICA IDENTITY FULL;
ALTER TABLE trip REPLICA IDENTITY FULL;
ALTER TABLE trip_container REPLICA IDENTITY FULL;
ALTER TABLE milestone REPLICA IDENTITY FULL;
ALTER TABLE handover REPLICA IDENTITY FULL;
ALTER TABLE incident REPLICA IDENTITY FULL;
ALTER TABLE event_log REPLICA IDENTITY FULL;
